Pass Time
OregonTrailGroup/Oregon-Trail-Scripting-Languages pull request #35
Opened 2017-05-02 16:17 UTC by adamwe1

Introduces PassTime.php (issue 22).  the file involves no javascript and uses $_GET to get the number of days to rest.  Let me know any logic errors.

2017-05-02 16:27 UTC, emanguy requested changes
Just a couple minor naming things. Clean those up and resubmit.

2017-05-02 16:27 UTC, emanguy commented on PassTime.php
> +?>
Because this is purely PHP you can just leave off the end tag. This avoids issues with trailing whitespace.

2017-05-02 16:27 UTC, emanguy commented on PassTime.php
> +$dateString = $_SESSION["journey"]->$_month . " " . $_SESSION["journey"]->$_date;
The agreed-upon key for the journey is "playerJourney". Also if you do arrow-syntax to a member variable you don't need the dollar sign in front of the member name.

You can see the agreed-upon keys in `$_SESSION` in the pinned post on slack under #general.

2017-05-02 16:27 UTC, emanguy commented on PassTime.php
> +return json_encode($associative_array);
echo json_encode, don't return. This isn't a function.

2017-05-02 16:28 UTC, emanguy commented on PassTime.php
> +?>
Oh also since this is a JSON response that will be interpreted by the JavaScript just get rid of any references to commonUI.

2017-05-07 03:44 UTC, emanguy requested changes
Just a couple more things to clean up, should be quick

2017-05-07 03:44 UTC, emanguy commented on PassTime.php
> +$time = $_GET["restDays"];
Make sure you run [intval()](http://php.net/manual/en/function.intval.php) on `$time`

2017-05-07 03:44 UTC, emanguy commented on PassTime.php
> +$dateString = $_SESSION["playerJourney"]->_month . " " . $_SESSION["playerJourney"]->_date;
Output the date in the format 1848-MONTH-DAY so it's easy to make a JS object on the frontend

2017-05-07 03:44 UTC, emanguy commented on Trade.php
> +	echo "A travaler wants to trade " . $itemAmount . " " . $itemClaim[$item] .
traveler

2017-05-08 19:29 UTC, eburch2 reviewed
as evan suggested you could technically leave off the ending php tags to remove the whitespacing

2017-05-10 15:43 UTC, emanguy approved these changes

2017-05-10 15:43 UTC, merged